#!/bin/bash

#
# Copies a user account from the production system
# to the staging environment.
#

set -e

if [ -z "$PGHOST" ]; then
  echo "Error: PGHOST not set in environment"
  exit 1
fi

if [ -z "$NEO4JHOST" ]; then
  echo "Error: NEO4JHOST not set in environment"
  exit 1
fi

USER=$1
if [ -z "$USER" ]; then
    echo "Arg should be a user ID!"
    exit 1
fi

EHRI_BASE=http://localhost:7474/ehri
EHRI_URL=$EHRI_BASE/classes/UserProfile

CURL_CMD="curl --netrc-file $HOME/.neo4j-netrc --silent --header X-User:admin --header Content-type:application/json"

psql --user docview_stage docview -c "\copy (SELECT * from users where id = '$1') TO STDOUT" | \
    psql --user docview_stage docview_stage -c "\copy users from stdin"

ssh "$NEO4JHOST" "curl -s $EHRI_URL/$USER" | $CURL_CMD --data-binary @- $EHRI_URL 

$CURL_CMD "$EHRI_BASE/entities?id=$USER" | java -jar /opt/webapps/docview/bin/indexer.jar --index  --file -

echo "Copied user $USER to from prod"
